import type { Metadata } from "next";
import WalletProvider from "@/wallet/provider";
import "./globals.css";
import ReduxProvider from "@/store";
import { headers } from "next/headers";
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'], weight: ['400', '600', '700'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
  
}>) {
  const headersList = await headers();
  const cookieHeader = headersList.get("cookie");
  return (
    <html lang="fa">
      <body className={inter.className}>
        <ReduxProvider>
          <WalletProvider cookies={cookieHeader}>
            {children}
          </WalletProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
